import express from 'express';
import { createServer as createViteServer } from 'vite';
import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { encodeFlac, demoWav } from './audio.js';
const app=express(), dir=path.resolve('data'); app.set('trust proxy',1); fs.mkdirSync(dir,{recursive:true});
const file=path.join(dir,'workstation.json');
let db=fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):{users:[],tokens:{},resources:{},audio:{}};
const save=()=>{fs.writeFileSync(file+'.tmp',JSON.stringify(db));fs.renameSync(file+'.tmp',file)};
const id=()=>randomBytes(12).toString('hex');
const hash=(p,s)=>scryptSync(p,s,64).toString('hex');
function seed(uid){db.resources[uid]={sessions:[{id:id(),name:'Midnight in the studio',type:'Music',description:'Live session · The Midnight Collective',date:'2026-10-04',duration:'24:38',tracks:4,format:'24-bit / 96 kHz',status:'In progress',color:'orange'},{id:id(),name:'The creative frequency',type:'Podcast',description:'Episode 028 · In conversation with Maya',date:'2026-10-03',duration:'48:12',tracks:2,format:'24-bit / 48 kHz',status:'Completed',color:'purple'},{id:id(),name:'Sunday, unplugged',type:'Music',description:'Acoustic guitar · Room B',date:'2026-10-02',duration:'12:45',tracks:3,format:'24-bit / 96 kHz',status:'Completed',color:'green'},{id:id(),name:'Field notes — city at dawn',type:'Field recording',description:'Ambience collection · Brooklyn',date:'2026-10-01',duration:'08:19',tracks:1,format:'24-bit / 48 kHz',status:'Completed',color:'blue'}],tracks:[],presets:[{id:id(),name:'Studio essentials',device:'Focusrite Scarlett 2i2',rate:'96000',depth:'24',channels:'Stereo',description:'Vocals & instruments',gain:32},{id:id(),name:'Podcast duo',device:'Zoom H6',rate:'48000',depth:'24',channels:'Stereo',description:'Two microphones · clean dialogue',gain:24},{id:id(),name:'High-resolution master',device:'USB DAC',rate:'384000',depth:'32',channels:'Stereo',description:'Native engine required',gain:0}],exports:[]};let r=db.resources[uid];const take=(name,sessionIndex,input,gain,color,recorded=false,rate=48000,depth=24,dur)=>({id:id(),name,sessionId:r.sessions[sessionIndex].id,input:`Input ${input}`,gain,muted:false,armed:false,color,recorded,recordedRate:recorded?rate:undefined,recordedDepth:recorded?depth:undefined,duration:dur||r.sessions[sessionIndex].duration});r.tracks=[take('Lead vocals',0,1,32,'orange',true,96000,24),take('Electric guitar',0,2,28,'purple'),take('Bass DI',0,3,24,'green',true,96000,24),take('Room microphone',0,4,20,'blue'),take('Host mic',1,1,26,'purple',true,48000,24),take('Guest mic',1,2,25,'orange',true,48000,24),take('Vocals & guitar',2,1,30,'green',true,96000,24),take('Room microphone',2,2,18,'blue'),take('Footswitch ambience',2,3,12,'purple'),take('Morning street bed',3,1,10,'blue',true,48000,24)];r.tracks[0].armed=true;r.tracks[1].armed=true;r.exports=[{id:id(),name:'Sunday unplugged — rough mix',sessionId:r.sessions[2].id,format:'WAV',date:'2026-10-02',status:'Demo preview',size:'0.5 MB',depth:'16',rate:'48000'}];save();}
const corsOrigins=new Set((process.env.CORS_ORIGINS||'capacitor://localhost,https://localhost,http://localhost').split(',').map(x=>x.trim()).filter(Boolean));
app.use((req,res,next)=>{const origin=req.headers.origin;if(origin&&corsOrigins.has(origin)){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Access-Control-Allow-Credentials','true');res.setHeader('Vary','Origin')}if(req.method==='OPTIONS'){res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,DELETE,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');res.setHeader('Access-Control-Max-Age','86400');return res.sendStatus(204)}next()});
app.use(express.json({limit:'100mb'}));
app.use((req,res,next)=>{const token=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith('audio_token='))?.split('=')[1];const t=db.tokens[token];if(t&&t.expires>Date.now())req.uid=t.uid;next()});
const auth=(req,res,next)=>req.uid?next():res.status(401).json({error:'Please sign in to continue.'});
function login(req,res,uid){const token=id();db.tokens[token]={uid,expires:Date.now()+7*86400000};save();const secure=req.secure||req.headers['x-forwarded-proto']==='https'||process.env.NODE_ENV==='production';res.cookie('audio_token',token,{httpOnly:true,sameSite:secure?'none':'lax',secure,partitioned:secure,maxAge:7*86400000});let u=db.users.find(u=>u.id===uid);res.json({id:u.id,name:u.name,email:u.email,demo:!!u.demo})}
app.post('/api/auth/demo',(req,res)=>{const uid=id();db.users.push({id:uid,name:'Alex Morgan',email:'alex@studio.audio',demo:true});seed(uid);login(req,res,uid)});
app.post('/api/auth/register',(req,res)=>{let {name,email,password}=req.body;email=email?.trim().toLowerCase();if(!name?.trim()||!/^\S+@\S+\.\S+$/.test(email||'')||typeof password!=='string'||password.length<8)return res.status(400).json({error:'Enter a name, valid email, and a password with at least 8 characters.'});if(db.users.some(u=>u.email===email&&!u.demo))return res.status(409).json({error:'An account with this email already exists.'});const salt=id(),uid=id();db.users.push({id:uid,name:name.trim(),email,salt,password:hash(password,salt)});seed(uid);login(req,res,uid)});
app.post('/api/auth/login',(req,res)=>{const u=db.users.find(u=>u.email===req.body.email?.trim().toLowerCase()&&!u.demo);if(!u||typeof req.body.password!=='string'||!timingSafeEqual(Buffer.from(u.password,'hex'),Buffer.from(hash(req.body.password,u.salt),'hex')))return res.status(401).json({error:'Email or password is incorrect.'});login(req,res,u.id)});
app.get('/api/auth/me',auth,(req,res)=>{const u=db.users.find(u=>u.id===req.uid);res.json({id:u.id,name:u.name,email:u.email,demo:!!u.demo})});
app.post('/api/auth/logout',(req,res)=>{const token=req.headers.cookie?.match(/audio_token=([^;]+)/)?.[1];delete db.tokens[token];save();const secure=req.secure||req.headers['x-forwarded-proto']==='https'||process.env.NODE_ENV==='production';res.clearCookie('audio_token',{httpOnly:true,sameSite:secure?'none':'lax',secure,partitioned:secure});res.json({ok:true})});
app.get('/api/workspace',auth,(req,res)=>res.json(db.resources[req.uid]));
const allowed=['sessions','tracks','presets','exports'];
app.use('/api/resources/:kind',auth,(req,res,next)=>allowed.includes(req.params.kind)?next():res.status(404).json({error:'Unknown resource'}));
app.post('/api/resources/:kind',auth,(req,res)=>{if(!req.body.name?.trim())return res.status(400).json({error:'A name is required.'});const r=db.resources[req.uid],kind=req.params.kind,item={...req.body,name:req.body.name.trim(),id:id()};if(kind==='sessions')item.tracks=0;if(kind==='tracks'){const session=r.sessions.find(x=>x.id===item.sessionId);if(!session)return res.status(400).json({error:'Choose a session for this track.'});session.tracks=(session.tracks||0)+1}if(kind==='exports'&&item.trackId){const source=r.tracks.find(t=>t.id===item.trackId);if(!source)return res.status(400).json({error:'Choose a valid source track.'});if(!source.recorded)return res.status(400).json({error:'Record this track before creating an export.'});if(!['WAV','FLAC'].includes(item.format))return res.status(400).json({error:'Choose WAV or FLAC.'});}r[kind].unshift(item);save();res.status(201).json(item)});
app.patch('/api/resources/:kind/:id',auth,(req,res)=>{const r=db.resources[req.uid],kind=req.params.kind,item=r[kind].find(x=>x.id===req.params.id);if(!item)return res.status(404).json({error:'Not found'});if(req.body.name!==undefined&&(!req.body.name||!req.body.name.trim()))return res.status(400).json({error:'A name is required.'});if(kind==='tracks'&&req.body.sessionId&&req.body.sessionId!==item.sessionId){const oldSession=r.sessions.find(x=>x.id===item.sessionId),newSession=r.sessions.find(x=>x.id===req.body.sessionId);if(!newSession)return res.status(400).json({error:'Choose a valid session.'});if(oldSession)oldSession.tracks=Math.max(0,(oldSession.tracks||0)-1);newSession.tracks=(newSession.tracks||0)+1}Object.assign(item,req.body,{id:item.id});save();res.json(item)});
app.delete('/api/resources/:kind/:id',auth,(req,res)=>{const r=db.resources[req.uid],kind=req.params.kind,item=r[kind].find(x=>x.id===req.params.id);if(kind==='sessions'){const removed=r.tracks.filter(t=>t.sessionId===req.params.id);removed.forEach(t=>delete db.audio[t.id]);r.tracks=r.tracks.filter(t=>t.sessionId!==req.params.id);r.exports=r.exports.filter(t=>t.sessionId!==req.params.id)}if(kind==='tracks'){if(item){const session=r.sessions.find(s=>s.id===item.sessionId);if(session)session.tracks=Math.max(0,(session.tracks||0)-1)}r.exports=r.exports.filter(x=>x.trackId!==req.params.id);delete db.audio[req.params.id]}r[kind]=r[kind].filter(x=>x.id!==req.params.id);save();res.json({ok:true})});
app.post('/api/audio/:id',auth,(req,res)=>{const r=db.resources[req.uid],t=r.tracks.find(x=>x.id===req.params.id);if(!t)return res.status(404).json({error:'Track not found'});if(typeof req.body.data!=='string')return res.status(400).json({error:'Missing recording'});const wav=Buffer.from(req.body.data,'base64'),rate=Number(req.body.rate)||48000,depth=Number(req.body.depth)||24;if(wav.length<44||wav.toString('ascii',0,4)!=='RIFF')return res.status(400).json({error:'The WAV recording is invalid.'});db.audio[t.id]={data:req.body.data,rate,depth};t.recorded=true;t.recordedRate=rate;t.recordedDepth=depth;t.duration=(()=>{const seconds=Math.floor(wav.readUInt32LE(40)/Math.max(1,wav.readUInt32LE(28)));return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`})();t.size=`${(wav.length/1048576).toFixed(1)} MB`;const session=r.sessions.find(x=>x.id===t.sessionId);if(session&&(!session.duration||session.duration==='00:00'))session.duration=t.duration;save();res.json({ok:true,duration:t.duration,size:t.size})});
app.get('/api/download/:id',auth,async(req,res)=>{const r=db.resources[req.uid],e=r.exports.find(x=>x.id===req.params.id),t=r.tracks.find(x=>x.id===req.params.id);if(!e&&!t)return res.status(404).json({error:'Not found'});const sourceTrack=t||r.tracks.find(x=>x.id===e?.trackId),a=db.audio[sourceTrack?.id],sampleRate=Number(sourceTrack?.recordedRate||e?.rate)||48000,bitDepth=Number(sourceTrack?.recordedDepth||e?.depth)||16;let source=a?Buffer.from(a.data,'base64'):demoWav(sampleRate,bitDepth),isFlac=e?.format==='FLAC';try{if(isFlac)source=await encodeFlac(source,e?.depth);const label=(t||e).name.replace(/[^a-zA-Z0-9 -]/g,'').trim()||'audio-rec';res.set('Content-Type',isFlac?'audio/flac':'audio/wav');res.set('Content-Disposition',`attachment; filename="${label}.${isFlac?'flac':'wav'}"`);res.send(source)}catch(err){console.error('FLAC encoding:',err.message);res.status(422).json({error:err.message||'Could not encode this FLAC file.'})}});
app.use((err,req,res,next)=>{console.error(err.message);res.status(400).json({error:err.type==='entity.too.large'?'Recording is too large. Use a shorter take.':'Unable to process the request.'})});
if(process.env.NODE_ENV==='production')app.use(express.static('dist'));else {const vite=await createViteServer({server:{middlewareMode:true,allowedHosts:true},appType:'spa'});app.use(vite.middlewares)}
const port=Number(process.env.PORT)||3000;app.listen(port,'0.0.0.0',()=>console.log(`AUDIO-rec listening on port ${port}`));
