#!/usr/bin/env python3
"""
AUDIO-rec :: official-logo brand pipeline.

The author's logo (assets/branding/audiorec-logo-user.svg - an illustrated
"REC / Hi-Res" phone with a USB plug and a waveform) is the brand now, so every
place the app shows the brand is generated from that one file:

    assets/branding/audiorec-logo-user-flat.svg   CSS baked into attributes
    assets/branding/audiorec-lockup-user.svg      logo + AUDIO-rec wordmark
    assets/branding/audiorec-lockup-user.png      same lockup, no fonts required
    assets/branding/audiorec-lockup-user-paper.png  ditto on the paper ground (readable
                                                  in any viewer, dark ink included)
    assets/branding/audiorec-mark-user.png        transparent raster (docs)
    assets/branding/audiorec-brand-preview.png    launcher-mask preview sheet
    res/mipmap-*/ic_launcher_foreground.png       adaptive-icon foreground (108dp)
    res/mipmap-anydpi-v26|v33/ic_launcher*.xml    adaptive-icon manifests

An adaptive icon (API 26+) wins over any density bucket, and AUDIO-rec needs
API 29+, so the old-style square/round PNGs are never what a launcher draws:
they are only built when LEGACY_PNGS is set, and the preview sheet keeps a
sample of them for the record.
    res/drawable-nodpi/brand_logo.png             full-colour logo for the UI

The artwork is black line art with warm ink (red REC, amber Hi-Res), so it needs
a *light* ground to read: the launcher plate is warm paper while the app UI
stays dark, and in the UI the logo sits on a paper plate of its own.

Rasterising needs the Rust `resvg` bindings:

    python3 -m pip install --break-system-packages resvg-py
    python3 tools/gen_brand.py

The generated files are committed, so a normal build never needs resvg.
"""
import io
import os
import re
import sys

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
RES = os.path.join(ROOT, "app", "src", "main", "res")
BRAND = os.path.join(ROOT, "assets", "branding")

SOURCE = os.path.join(BRAND, "audiorec-logo-user.svg")
FLAT = os.path.join(BRAND, "audiorec-logo-user-flat.svg")
LOCKUP = os.path.join(BRAND, "audiorec-lockup-user.svg")

PAPER = (0xF7, 0xF5, 0xF1)          # launcher ground - flatters the warm ink
PAPER_HEX = "#F7F5F1"
INK = (0x0A, 0x0D, 0x12)
RED = "#F90000"                      # the REC wordmark red, straight from the art
AMBER = "#FF8B1F"                    # the Hi-Res amber
WORD_INK = "#0A0D12"
MUTED = "#9AACBF"

# density buckets: (folder, legacy px, adaptive-foreground px = 108dp)
DENSITIES = (("mdpi", 48, 108), ("hdpi", 72, 162), ("xhdpi", 96, 216),
             ("xxhdpi", 144, 324), ("xxxhdpi", 192, 432))

# minSdk is 29, so the adaptive icon always wins: ship the foreground + the
# manifests only. Flip this if the icon ever has to survive on API < 26.
LEGACY_PNGS = False

ADAPTIVE_XML = """<?xml version="1.0" encoding="utf-8"?>
<!-- AUDIO-rec adaptive launcher icon: the official logo on a warm paper ground.
     Generated by tools/gen_brand.py - edit that, not this. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
%s</adaptive-icon>
"""

MONO_LAYER = '    <monochrome android:drawable="@drawable/ic_launcher_mono" />\n'


# --------------------------------------------------------------------- steps --
def flatten_source():
    sys.path.insert(0, HERE)
    from svg_flatten import flatten

    text = open(SOURCE, encoding="utf-8").read()
    out = flatten(text)
    with open(FLAT, "w", encoding="utf-8") as f:
        f.write(out)
    print("  assets/branding/audiorec-logo-user-flat.svg")
    return out


def render(svg_text, width):
    import resvg_py                                  # Rust usvg bindings
    png = resvg_py.svg_to_bytes(svg_string=svg_text, width=width)
    return Image.open(io.BytesIO(png)).convert("RGBA")


def fit(img, box_w, box_h):
    s = min(box_w / img.size[0], box_h / img.size[1])
    return img.resize((max(1, int(round(img.size[0] * s))),
                       max(1, int(round(img.size[1] * s)))), Image.LANCZOS)


def centre(canvas, layer, y=None):
    x = (canvas.size[0] - layer.size[0]) // 2
    if y is None:
        y = (canvas.size[1] - layer.size[1]) // 2
    canvas.alpha_composite(layer, (x, y))
    return canvas


def inner_svg(svg_text):
    """everything between the root <svg ...> tag and </svg>"""
    a = svg_text.index(">", svg_text.index("<svg")) + 1
    b = svg_text.rindex("</svg>")
    return svg_text[a:b].strip()


def write(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    mode = "wb" if isinstance(data, bytes) else "w"
    with open(path, mode) as f:
        f.write(data)
    print("  %s" % os.path.relpath(path, ROOT))


# --------------------------------------------------------------------- icons --
def legacy_icon(art, size, round_shape=False):
    """square/round plate, ink outline, logo centred - what old launchers show"""
    ss = 4
    S = size * ss
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    dr = ImageDraw.Draw(img)
    stroke = max(2, int(round(S * 0.026)))
    if round_shape:
        dr.ellipse([0, 0, S - 1, S - 1], fill=PAPER + (255,), outline=INK + (255,), width=stroke)
        logo = fit(art, S * 0.60, S * 0.60)
    else:
        dr.rounded_rectangle([0, 0, S - 1, S - 1], radius=S * 0.22, fill=PAPER + (255,),
                             outline=INK + (255,), width=stroke)
        logo = fit(art, S * 0.66, S * 0.68)
    centre(img, logo)
    return img.resize((size, size), Image.LANCZOS)


def adaptive_foreground(art, size):
    """transparent 108dp layer; artwork kept inside the 66dp safe circle"""
    ss = 4
    S = size * ss
    img = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    centre(img, fit(art, S * 0.60, S * 0.56))
    return img.resize((size, size), Image.LANCZOS)


# ------------------------------------------------------------------- lockup ---
def lockup_svg(flat_text):
    inner = inner_svg(flat_text)
    H = 760.0
    art_h = 700.0
    art_w = art_h * 926.56 / 1232.56
    tx = 60 + art_w + 90
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<!-- AUDIO-rec lockup: the official logo beside the wordmark.\n'
            '     Generated by tools/gen_brand.py from audiorec-logo-user.svg. -->\n'
            '<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="%g" '
            'viewBox="0 0 1600 %g">\n'
            '  <g transform="translate(60,30) scale(%g)">\n%s\n  </g>\n'
            '  <text x="%g" y="355" font-family="Helvetica,Arial,sans-serif" font-size="150" '
            'font-weight="700" fill="%s" letter-spacing="-4">AUDIO<tspan fill="%s">-rec</tspan></text>\n'
            '  <text x="%g" y="425" font-family="Helvetica,Arial,sans-serif" font-size="38" '
            'fill="%s" letter-spacing="7">USB AUDIO RECORDING &amp; PRODUCTION WORKSTATION</text>\n'
            '  <text x="%g" y="510" font-family="Helvetica,Arial,sans-serif" font-size="34" '
            'fill="%s">by Mostakim Billah</text>\n'
            '</svg>\n'
            % (H, H, art_h / 1232.56, inner, tx, WORD_INK, RED, tx, AMBER, tx, MUTED))


def lockup_png(art):
    """font-independent copy of the lockup: resvg in this sandbox has no text
    support (it silently drops <text>), so the docs copy is drawn with PIL."""
    W, H = 1600, 760
    img = Image.new("RGBA", (W, H), (255, 255, 255, 0))
    dr = ImageDraw.Draw(img)

    def font(px, bold=False):
        try:
            return ImageFont.truetype(
                "/usr/share/fonts/truetype/dejavu/DejaVuSans%s.ttf" % ("-Bold" if bold else ""), px)
        except Exception:
            return ImageFont.load_default()

    def spaced(text, x, y, px, fill, extra, bold=False):
        """PIL cannot letter-space, so place one glyph at a time"""
        f = font(px, bold)
        for ch in text:
            dr.text((x, y), ch, font=f, fill=fill)
            x += dr.textlength(ch, font=f) + extra
        return x

    def spaced_w(text, px, extra, bold=False):
        f = font(px, bold)
        return sum(dr.textlength(ch, font=f) + extra for ch in text) - extra

    logo = fit(art, W * 0.40, H * 0.82)
    img.alpha_composite(logo, (44, int((H - logo.size[1]) / 2.0)))
    x = 44 + logo.size[0] + 76
    avail = W - x - 40

    px = int(H * 0.20)                                  # wordmark
    while px > 24 and dr.textlength("AUDIO-rec", font=font(px, True)) > avail:
        px -= 2
    wf = font(px, True)
    ty = int(H * 0.30)
    dr.text((x, ty), "AUDIO", font=wf, fill=INK + (255,))
    dr.text((x + dr.textlength("AUDIO", font=wf), ty), "-rec", font=wf, fill=(0xF9, 0x00, 0x00, 255))

    px = int(H * 0.044)                                 # tagline, letter-spaced
    ex = max(2, int(px * 0.14))
    while px > 12 and spaced_w("USB AUDIO RECORDING & PRODUCTION WORKSTATION", px, ex) > avail:
        px -= 1
        ex = max(2, int(px * 0.14))
    spaced("USB AUDIO RECORDING & PRODUCTION WORKSTATION", x, int(H * 0.585), px,
           (0xFF, 0x8B, 0x1F, 255), ex)
    dr.text((x, int(H * 0.72)), "by Mostakim Billah", font=font(int(H * 0.050)),
            fill=(0x9A, 0xAC, 0xBF, 255))
    return img


# ------------------------------------------------------------------ preview ---
def label(dr, x, y, text, align="left"):
    try:
        f = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 20)
    except Exception:
        f = None
    if align == "center":
        w = dr.textlength(text, font=f)
        x -= w / 2
    dr.text((x, y), text, font=f, fill=(154, 172, 191, 255))


def preview_sheet(art):
    """show the reader how the icon survives each launcher mask"""
    T = 300
    ss = 2
    sheet = Image.new("RGBA", (T * 3 * ss, (T + 60) * ss), (10, 13, 18, 255))
    dr = ImageDraw.Draw(sheet)
    fg = adaptive_foreground(art, T * ss)
    paper = Image.new("RGBA", (T * ss, T * ss), PAPER + (255,))
    plate = Image.alpha_composite(paper, fg)
    masks = {
        "square": None,
        "circle": Image.new("L", (T * ss, T * ss), 0),
        "squircle": Image.new("L", (T * ss, T * ss), 0),
    }
    ImageDraw.Draw(masks["circle"]).ellipse([0, 0, T * ss - 1, T * ss - 1], fill=255)
    ImageDraw.Draw(masks["squircle"]).rounded_rectangle([0, 0, T * ss - 1, T * ss - 1],
                                                        radius=int(T * ss * 0.30), fill=255)
    # the legacy PNG has no mask, so also show it blown up next to its 48dp self
    legacy = legacy_icon(art, T * ss // 4).resize((T * ss, T * ss), Image.NEAREST)
    for i, (name, mask) in enumerate(masks.items()):
        if mask is None:
            tile = legacy
        else:
            # keep the mask as real alpha so the shape reads against the sheet
            tile = plate.copy()
            tile.putalpha(mask)
        sheet.alpha_composite(tile, (i * T * ss, 0))
        label(dr, i * T * ss + T * ss // 2, T * ss + 16,
              "%s mask%s" % (name, " (legacy 48dp, 4x)" if mask is None else ""), "center")
    return sheet


# --------------------------------------------------------------------- main ---
def main():
    print("AUDIO-rec :: brand icons from the official logo")
    if not os.path.exists(SOURCE):
        print("  ! %s is missing - the official logo is the source of truth."
              % os.path.relpath(SOURCE, ROOT))
        return 1
    flat = flatten_source()
    try:
        art = render(flat, 2048)
    except Exception as exc:                                        # pragma: no cover
        print("  ! rasteriser unavailable (%s: %s)" % (type(exc).__name__, exc))
        print("    python3 -m pip install --break-system-packages resvg-py")
        return 1
    print("  rasterised logo: %dx%d" % art.size)

    # ---- legacy raster launcher icons + adaptive foregrounds
    for dpi, legacy_px, fg_px in DENSITIES:
        d = os.path.join(RES, "mipmap-" + dpi)
        if LEGACY_PNGS:
            legacy_icon(art, legacy_px).save(os.path.join(d, "ic_launcher.png"))
            legacy_icon(art, legacy_px, round_shape=True).save(
                os.path.join(d, "ic_launcher_round.png"))
        adaptive_foreground(art, fg_px).save(os.path.join(d, "ic_launcher_foreground.png"))
        print("  res/mipmap-%s/ic_launcher_foreground.png%s"
              % (dpi, "  (+ ic_launcher.png, +_round)" if LEGACY_PNGS else ""))

    # ---- adaptive-icon manifests (v26 plain, v33 adds the themed layer)
    for api, extra in (("v26", ""), ("v33", MONO_LAYER)):
        for name in ("ic_launcher", "ic_launcher_round"):
            write(os.path.join(RES, "mipmap-anydpi-" + api, name + ".xml"),
                  ADAPTIVE_XML % extra)

    # ---- full-colour logo for the UI (About screen shows it on a paper plate)
    logo_ui = art.resize((512, int(round(art.size[1] * 512.0 / art.size[0]))), Image.LANCZOS)
    buf = io.BytesIO()
    logo_ui.save(buf, "PNG", optimize=True)
    write(os.path.join(RES, "drawable-nodpi", "brand_logo.png"), buf.getvalue())

    # ---- docs / repo branding
    buf = io.BytesIO()
    art.resize((1024, int(round(art.size[1] * 1024.0 / art.size[0]))), Image.LANCZOS) \
       .save(buf, "PNG", optimize=True)
    write(os.path.join(BRAND, "audiorec-mark-user.png"), buf.getvalue())
    write(LOCKUP, lockup_svg(flat))
    lockup = lockup_png(art)
    write(os.path.join(BRAND, "audiorec-lockup-user.png"), _png_bytes(lockup))
    # the wordmark is near-black ink, so a transparent copy reads as a hole on a
    # dark viewer: keep an opaque paper-backed copy next to it
    paper = Image.new("RGBA", lockup.size, PAPER + (255,))
    paper.alpha_composite(lockup)
    write(os.path.join(BRAND, "audiorec-lockup-user-paper.png"), _png_bytes(paper))
    write(os.path.join(BRAND, "audiorec-brand-preview.png"), _png_bytes(preview_sheet(art)))
    return 0


def _png_bytes(img):
    buf = io.BytesIO()
    img.save(buf, "PNG", optimize=True)
    return buf.getvalue()


if __name__ == "__main__":
    sys.exit(main())
